name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, deploy]
    environment: production

    steps:
      - uses: actions/checkout@v4
      - name: copy repository
        uses: appleboy/scp-action@v1
        with:
          host: ${{ vars.HOST }}
          username: ${{ vars.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "*,!.git,!.github,!.gitignore"
          target: /home/research-profiles/production/research-profiles-api
          rm: true
      - name: install dependencies
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ vars.HOST }}
          username: ${{ vars.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/research-profiles/production/research-profiles-api
            npm install --omit=dev
      - name: restart the service
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ vars.HOST }}
          username: ${{ vars.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            systemctl --user restart research-profiles-api-prod.service
